server:
  port: 5896
eureka:
  instance:
    lease-expiration-duration-in-seconds: 5
    leaseRenewalIntervalInSeconds: 5
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: Employee-Services
    
      
      
  